root = "\\GETOOLS_SOURCE"

get = root + "\icons\GET.png"
tools = root + "\icons\Tools.png"
centerOfMass = root + "\icons\CenterOfMass.png"
overlappy = root + "\icons\Overlappy.png"

# Maya's
empty = "empty.png"
bookmark = "Bookmark.png"
help = "help.png"
error = "error.png"
warning = "warningIcon.svg"
visible = "visible.png"
light = "Light.png"
playblast = "playblast.png"
wait = "waitBusy.png"
list = "list.svg"
layer = "layerEditor.png"
zoom = "zoom.png"